### ISSUE TITLE
Undefined array key "request"

### ISSUE THREAD

**Issue by JastinXyz** [chrysanthos/pulse-requests#1]
when I just installed it and did what was done in README.md then I checked it and the error immediately occurred. Oh BTW I use the 1.0 version.

![image](https://github.com/chrysanthos/pulse-requests/assets/73673322/e9bc96c5-d48e-419c-8a3e-9de753b892b7)

After some searching I think the error lines are https://github.com/chrysanthos/pulse-requests/blob/83ee911927617162b3c98366bec233dffb45db8f/src/Livewire/Requests.php#L26 and https://github.com/chrysanthos/pulse-requests/blob/83ee911927617162b3c98366bec233dffb45db8f/src/Livewire/Requests.php#L22
Because the "request" prop is not in "requests" collection I think.

But I'm not sure what to do, because I don't know how the Laravel Pulse card works.

**Comment by chrysanthos** [comment]
Hey @JastinXyz, I just released version 1.0.5 which fixes this. Let me know if it works for you too.
